In [1]:
from sklearn.svm import SVC
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import datasets

In [2]:
df = datasets.load_iris(as_frame=True).frame

In [3]:
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [4]:
X = df.drop("target", axis=1)
y = df["target"]

In [5]:
X.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [7]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [8]:
X_train.head()

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
8                  4.4               2.9                1.4               0.2
106                4.9               2.5                4.5               1.7
76                 6.8               2.8                4.8               1.4
9                  4.9               3.1                1.5               0.1
89                 5.5               2.5                4.0               1.3

In [9]:
from sklearn.preprocessing import StandardScaler

scalar = StandardScaler()
X_train_scaled = scalar.fit_transform(X_train)
X_test_scaled = scalar.transform(X_test)

In [10]:
# model

svc = SVC()
svc.fit(X_train_scaled, y_train)

SVC()

In [11]:
y_pred = svc.predict(X_test_scaled)

In [16]:
from sklearn.metrics import accuracy_score, classification_report, f1_score

print("Accuracy : ", accuracy_score(y_test, y_pred))
print("Classification Report : \n", classification_report(y_test, y_pred))

Accuracy :  0.9666666666666667
Classification Report :
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.90      0.95        10
           2       0.91      1.00      0.95        10

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30

In [18]:
# Linear Kernel

svc = SVC(kernel="linear")
svc.fit(X_train_scaled, y_train)
y_pred = svc.predict(X_test_scaled)
print("Accuracy : ", accuracy_score(y_test, y_pred))
print("Classification Report : \n", classification_report(y_test, y_pred))

Accuracy :  1.0
Classification Report :
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00        10
           2       1.00      1.00      1.00        10

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

In [19]:
# Polynomial Kernel

svc = SVC(kernel="poly")
svc.fit(X_train_scaled, y_train)
y_pred = svc.predict(X_test_scaled)
print("Accuracy : ", accuracy_score(y_test, y_pred))
print("Classification Report : \n", classification_report(y_test, y_pred))

Accuracy :  0.9
Classification Report :
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.77      1.00      0.87        10
           2       1.00      0.70      0.82        10

    accuracy                           0.90        30
   macro avg       0.92      0.90      0.90        30
weighted avg       0.92      0.90      0.90        30

In [20]:
# sigmoid Kernel

svc = SVC(kernel="sigmoid")
svc.fit(X_train_scaled, y_train)
y_pred = svc.predict(X_test_scaled)
print("Accuracy : ", accuracy_score(y_test, y_pred))
print("Classification Report : \n", classification_report(y_test, y_pred))

Accuracy :  0.9
Classification Report :
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.70      0.82        10
           2       0.77      1.00      0.87        10

    accuracy                           0.90        30
   macro avg       0.92      0.90      0.90        30
weighted avg       0.92      0.90      0.90        30

In [22]:
C_vals = [1, 2, 3, 4, 5]

# Linear Kernel
for c_val in C_vals:

    svc = SVC(kernel="rbf", C=c_val)
    svc.fit(X_train_scaled, y_train)
    y_pred = svc.predict(X_test_scaled)
    print(f"C : {c_val} - - Accuracy : ", accuracy_score(y_test, y_pred))

C : 1 - - Accuracy :  0.9666666666666667
C : 2 - - Accuracy :  0.9333333333333333
C : 3 - - Accuracy :  0.9666666666666667
C : 4 - - Accuracy :  0.9666666666666667
C : 5 - - Accuracy :  0.9666666666666667