In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("./data/employees.csv")
print(df.head(10))

   emp_id   name department   salary  age joining_date       city
0       1   Amit         IT  75000.0   29   2021-03-15       Pune
1       2   Riya         HR  45000.0   26   2020-07-10     Mumbai
2       3   John    Finance  85000.0   34   2019-11-01  Bangalore
3       4   Neha         IT  65000.0   28   2022-01-20       Pune
4       5  Arjun  Marketing  40000.0   25   2021-06-18      Delhi
5       6  Priya    Finance  90000.0   36   2018-04-25     Mumbai
6       7  Karan         HR  48000.0   27   2022-09-12       Pune
7       8  Sneha         IT  72000.0   31   2020-12-05  Bangalore
8       9  Rahul  Marketing  52000.0   30   2019-02-14      Delhi
9      10  Pooja    Finance  88000.0   35   2021-08-30       Pune

In [4]:
# df.shape
df.info

<bound method DataFrame.info of     emp_id    name department   salary  age joining_date       city
0        1    Amit         IT  75000.0   29   2021-03-15       Pune
1        2    Riya         HR  45000.0   26   2020-07-10     Mumbai
2        3    John    Finance  85000.0   34   2019-11-01  Bangalore
3        4    Neha         IT  65000.0   28   2022-01-20       Pune
4        5   Arjun  Marketing  40000.0   25   2021-06-18      Delhi
5        6   Priya    Finance  90000.0   36   2018-04-25     Mumbai
6        7   Karan         HR  48000.0   27   2022-09-12       Pune
7        8   Sneha         IT  72000.0   31   2020-12-05  Bangalore
8        9   Rahul  Marketing  52000.0   30   2019-02-14      Delhi
9       10   Pooja    Finance  88000.0   35   2021-08-30       Pune
10      11  Vikram         IT  60000.0   33   2018-05-21     Mumbai
11      12  Anjali         HR      NaN   29   2023-03-11      Delhi
12      13   Rohan         IT  55000.0   26   2022-11-19       Pune
13      14  Simran  Marketing  47000.0   28   2020-01-10  Bangalore
14      15  Deepak    Finance      NaN   32   2019-09-17      Delhi
15      16   Nisha         IT  80000.0   34   2017-06-23     Mumbai
16      17   Sahil         HR  42000.0   24   2023-01-05       Pune
17      18    Tina  Marketing  51000.0   29   2021-04-14     Mumbai
18      19   Varun    Finance  95000.0   38   2016-10-09  Bangalore
19      20   Meera         IT  70000.0   31   2020-02-27      Delhi>

In [5]:
df2 = df[["name", "department", "salary"]]
df2

      name department   salary
0     Amit         IT  75000.0
1     Riya         HR  45000.0
2     John    Finance  85000.0
3     Neha         IT  65000.0
4    Arjun  Marketing  40000.0
5    Priya    Finance  90000.0
6    Karan         HR  48000.0
7    Sneha         IT  72000.0
8    Rahul  Marketing  52000.0
9    Pooja    Finance  88000.0
10  Vikram         IT  60000.0
11  Anjali         HR      NaN
12   Rohan         IT  55000.0
13  Simran  Marketing  47000.0
14  Deepak    Finance      NaN
15   Nisha         IT  80000.0
16   Sahil         HR  42000.0
17    Tina  Marketing  51000.0
18   Varun    Finance  95000.0
19   Meera         IT  70000.0

In [6]:
empSalary = df[(df["salary"] > 50000)]
empSalary

    emp_id    name department   salary  age joining_date       city
0        1    Amit         IT  75000.0   29   2021-03-15       Pune
2        3    John    Finance  85000.0   34   2019-11-01  Bangalore
3        4    Neha         IT  65000.0   28   2022-01-20       Pune
5        6   Priya    Finance  90000.0   36   2018-04-25     Mumbai
7        8   Sneha         IT  72000.0   31   2020-12-05  Bangalore
8        9   Rahul  Marketing  52000.0   30   2019-02-14      Delhi
9       10   Pooja    Finance  88000.0   35   2021-08-30       Pune
10      11  Vikram         IT  60000.0   33   2018-05-21     Mumbai
12      13   Rohan         IT  55000.0   26   2022-11-19       Pune
15      16   Nisha         IT  80000.0   34   2017-06-23     Mumbai
17      18    Tina  Marketing  51000.0   29   2021-04-14     Mumbai
18      19   Varun    Finance  95000.0   38   2016-10-09  Bangalore
19      20   Meera         IT  70000.0   31   2020-02-27      Delhi

In [7]:
deptEmpCount = df["department"].value_counts()
deptEmpCount

department
IT           7
Finance      5
HR           4
Marketing    4
Name: count, dtype: int64

In [8]:
df["city"].unique()

array(['Pune', 'Mumbai', 'Bangalore', 'Delhi'], dtype=object)

In [9]:
df_sorted = df.sort_values(by="salary", ascending=False)
df_sorted

    emp_id    name department   salary  age joining_date       city
18      19   Varun    Finance  95000.0   38   2016-10-09  Bangalore
5        6   Priya    Finance  90000.0   36   2018-04-25     Mumbai
9       10   Pooja    Finance  88000.0   35   2021-08-30       Pune
2        3    John    Finance  85000.0   34   2019-11-01  Bangalore
15      16   Nisha         IT  80000.0   34   2017-06-23     Mumbai
0        1    Amit         IT  75000.0   29   2021-03-15       Pune
7        8   Sneha         IT  72000.0   31   2020-12-05  Bangalore
19      20   Meera         IT  70000.0   31   2020-02-27      Delhi
3        4    Neha         IT  65000.0   28   2022-01-20       Pune
10      11  Vikram         IT  60000.0   33   2018-05-21     Mumbai
12      13   Rohan         IT  55000.0   26   2022-11-19       Pune
8        9   Rahul  Marketing  52000.0   30   2019-02-14      Delhi
17      18    Tina  Marketing  51000.0   29   2021-04-14     Mumbai
6        7   Karan         HR  48000.0   27   2022-09-12       Pune
13      14  Simran  Marketing  47000.0   28   2020-01-10  Bangalore
1        2    Riya         HR  45000.0   26   2020-07-10     Mumbai
16      17   Sahil         HR  42000.0   24   2023-01-05       Pune
4        5   Arjun  Marketing  40000.0   25   2021-06-18      Delhi
11      12  Anjali         HR      NaN   29   2023-03-11      Delhi
14      15  Deepak    Finance      NaN   32   2019-09-17      Delhi

In [10]:
df["salary"].mean()

np.float64(64444.444444444445)

In [11]:
df.rename(columns={"joining_date": "doj"}, inplace=True)

In [12]:
df_sal = df.sort_values(by="salary", ascending=False)

df_sal[0:3]

    emp_id   name department   salary  age         doj       city
18      19  Varun    Finance  95000.0   38  2016-10-09  Bangalore
5        6  Priya    Finance  90000.0   36  2018-04-25     Mumbai
9       10  Pooja    Finance  88000.0   35  2021-08-30       Pune

In [13]:
df_age = df[(df["age"] >= 25) & (df["age"] <= 35)]
df_age

    emp_id    name department   salary  age         doj       city
0        1    Amit         IT  75000.0   29  2021-03-15       Pune
1        2    Riya         HR  45000.0   26  2020-07-10     Mumbai
2        3    John    Finance  85000.0   34  2019-11-01  Bangalore
3        4    Neha         IT  65000.0   28  2022-01-20       Pune
4        5   Arjun  Marketing  40000.0   25  2021-06-18      Delhi
6        7   Karan         HR  48000.0   27  2022-09-12       Pune
7        8   Sneha         IT  72000.0   31  2020-12-05  Bangalore
8        9   Rahul  Marketing  52000.0   30  2019-02-14      Delhi
9       10   Pooja    Finance  88000.0   35  2021-08-30       Pune
10      11  Vikram         IT  60000.0   33  2018-05-21     Mumbai
11      12  Anjali         HR      NaN   29  2023-03-11      Delhi
12      13   Rohan         IT  55000.0   26  2022-11-19       Pune
13      14  Simran  Marketing  47000.0   28  2020-01-10  Bangalore
14      15  Deepak    Finance      NaN   32  2019-09-17      Delhi
15      16   Nisha         IT  80000.0   34  2017-06-23     Mumbai
17      18    Tina  Marketing  51000.0   29  2021-04-14     Mumbai
19      20   Meera         IT  70000.0   31  2020-02-27      Delhi

In [14]:
df["salary_after_tax"] = df["salary"] - (df["salary"] * 0.1)
df

,emp_id,name,department,salary,age,doj,city,salary_after_tax
0,1,Amit,IT,75000.0,29,2021-03-15,Pune,67500.0
1,2,Riya,HR,45000.0,26,2020-07-10,Mumbai,40500.0
2,3,John,Finance,85000.0,34,2019-11-01,Bangalore,76500.0
3,4,Neha,IT,65000.0,28,2022-01-20,Pune,58500.0
4,5,Arjun,Marketing,40000.0,25,2021-06-18,Delhi,36000.0
5,6,Priya,Finance,90000.0,36,2018-04-25,Mumbai,81000.0
6,7,Karan,HR,48000.0,27,2022-09-12,Pune,43200.0
7,8,Sneha,IT,72000.0,31,2020-12-05,Bangalore,64800.0
8,9,Rahul,Marketing,52000.0,30,2019-02-14,Delhi,46800.0
9,10,Pooja,Finance,88000.0,35,2021-08-30,Pune,79200.0
10,11,Vikram,IT,60000.0,33,2018-05-21,Mumbai,54000.0
11,12,Anjali,HR,NaN,29,2023-03-11,Delhi,NaN
12,13,Rohan,IT,55000.0,26,2022-11-19,Pune,49500.0
13,14,Simran,Marketing,47000.0,28,2020-01-10,Bangalore,42300.0
14,15,Deepak,Finance,NaN,32,2019-09-17,Delhi,NaN
15,16,Nisha,IT,80000.0,34,2017-06-23,Mumbai,72000.0
16,17,Sahil,HR,42000.0,24,2023-01-05,Pune,37800.0
17,18,Tina,Marketing,51000.0,29,2021-04-14,Mumbai,45900.0
18,19,Varun,Finance,95000.0,38,2016-10-09,Bangalore,85500.0
19,20,Meera,IT,70000.0,31,2020-02-27,Delhi,63000.0

In [15]:
df["joining_date_time"] = pd.to_datetime(df["doj"])
df

,emp_id,name,department,salary,age,doj,city,salary_after_tax,joining_date_time
0,1,Amit,IT,75000.0,29,2021-03-15,Pune,67500.0,2021-03-15
1,2,Riya,HR,45000.0,26,2020-07-10,Mumbai,40500.0,2020-07-10
2,3,John,Finance,85000.0,34,2019-11-01,Bangalore,76500.0,2019-11-01
3,4,Neha,IT,65000.0,28,2022-01-20,Pune,58500.0,2022-01-20
4,5,Arjun,Marketing,40000.0,25,2021-06-18,Delhi,36000.0,2021-06-18
5,6,Priya,Finance,90000.0,36,2018-04-25,Mumbai,81000.0,2018-04-25
6,7,Karan,HR,48000.0,27,2022-09-12,Pune,43200.0,2022-09-12
7,8,Sneha,IT,72000.0,31,2020-12-05,Bangalore,64800.0,2020-12-05
8,9,Rahul,Marketing,52000.0,30,2019-02-14,Delhi,46800.0,2019-02-14
9,10,Pooja,Finance,88000.0,35,2021-08-30,Pune,79200.0,2021-08-30
10,11,Vikram,IT,60000.0,33,2018-05-21,Mumbai,54000.0,2018-05-21
11,12,Anjali,HR,NaN,29,2023-03-11,Delhi,NaN,2023-03-11
12,13,Rohan,IT,55000.0,26,2022-11-19,Pune,49500.0,2022-11-19
13,14,Simran,Marketing,47000.0,28,2020-01-10,Bangalore,42300.0,2020-01-10
14,15,Deepak,Finance,NaN,32,2019-09-17,Delhi,NaN,2019-09-17
15,16,Nisha,IT,80000.0,34,2017-06-23,Mumbai,72000.0,2017-06-23
16,17,Sahil,HR,42000.0,24,2023-01-05,Pune,37800.0,2023-01-05
17,18,Tina,Marketing,51000.0,29,2021-04-14,Mumbai,45900.0,2021-04-14
18,19,Varun,Finance,95000.0,38,2016-10-09,Bangalore,85500.0,2016-10-09
19,20,Meera,IT,70000.0,31,2020-02-27,Delhi,63000.0,2020-02-27

In [16]:
df_doj = df[(df["joining_date_time"] > "2021-01-01")]
df_doj

,emp_id,name,department,salary,age,doj,city,salary_after_tax,joining_date_time
0,1,Amit,IT,75000.0,29,2021-03-15,Pune,67500.0,2021-03-15
3,4,Neha,IT,65000.0,28,2022-01-20,Pune,58500.0,2022-01-20
4,5,Arjun,Marketing,40000.0,25,2021-06-18,Delhi,36000.0,2021-06-18
6,7,Karan,HR,48000.0,27,2022-09-12,Pune,43200.0,2022-09-12
9,10,Pooja,Finance,88000.0,35,2021-08-30,Pune,79200.0,2021-08-30
11,12,Anjali,HR,NaN,29,2023-03-11,Delhi,NaN,2023-03-11
12,13,Rohan,IT,55000.0,26,2022-11-19,Pune,49500.0,2022-11-19
16,17,Sahil,HR,42000.0,24,2023-01-05,Pune,37800.0,2023-01-05
17,18,Tina,Marketing,51000.0,29,2021-04-14,Mumbai,45900.0,2021-04-14

In [17]:
city = df.groupby("city")["salary"].mean()
city

max_salary = df.groupby("city")["salary"].max()
max_salary

employee_count = df.groupby("city")["emp_id"].count()
employee_count

city
Bangalore    4
Delhi        5
Mumbai       5
Pune         6
Name: emp_id, dtype: int64

In [18]:
# df.groupby('department')['salary'].mean()
df["salary"] = df["salary"].fillna(df.groupby("department")["salary"].transform("mean"))
df

,emp_id,name,department,salary,age,doj,city,salary_after_tax,joining_date_time
0,1,Amit,IT,75000.0,29,2021-03-15,Pune,67500.0,2021-03-15
1,2,Riya,HR,45000.0,26,2020-07-10,Mumbai,40500.0,2020-07-10
2,3,John,Finance,85000.0,34,2019-11-01,Bangalore,76500.0,2019-11-01
3,4,Neha,IT,65000.0,28,2022-01-20,Pune,58500.0,2022-01-20
4,5,Arjun,Marketing,40000.0,25,2021-06-18,Delhi,36000.0,2021-06-18
5,6,Priya,Finance,90000.0,36,2018-04-25,Mumbai,81000.0,2018-04-25
6,7,Karan,HR,48000.0,27,2022-09-12,Pune,43200.0,2022-09-12
7,8,Sneha,IT,72000.0,31,2020-12-05,Bangalore,64800.0,2020-12-05
8,9,Rahul,Marketing,52000.0,30,2019-02-14,Delhi,46800.0,2019-02-14
9,10,Pooja,Finance,88000.0,35,2021-08-30,Pune,79200.0,2021-08-30
10,11,Vikram,IT,60000.0,33,2018-05-21,Mumbai,54000.0,2018-05-21
11,12,Anjali,HR,45000.0,29,2023-03-11,Delhi,NaN,2023-03-11
12,13,Rohan,IT,55000.0,26,2022-11-19,Pune,49500.0,2022-11-19
13,14,Simran,Marketing,47000.0,28,2020-01-10,Bangalore,42300.0,2020-01-10
14,15,Deepak,Finance,89500.0,32,2019-09-17,Delhi,NaN,2019-09-17
15,16,Nisha,IT,80000.0,34,2017-06-23,Mumbai,72000.0,2017-06-23
16,17,Sahil,HR,42000.0,24,2023-01-05,Pune,37800.0,2023-01-05
17,18,Tina,Marketing,51000.0,29,2021-04-14,Mumbai,45900.0,2021-04-14
18,19,Varun,Finance,95000.0,38,2016-10-09,Bangalore,85500.0,2016-10-09
19,20,Meera,IT,70000.0,31,2020-02-27,Delhi,63000.0,2020-02-27

In [19]:
# import numpy as np
# today = pd.to_datetime('now')

# df['experience_years'] =  (today - df['joining_date_time']) / np.timedelta64(1 , 'Y')

today = pd.Timestamp.today()

df["experience_years"] = round((today - df["joining_date_time"]).dt.days / 365.25, 2)
df

,emp_id,name,department,salary,age,doj,city,salary_after_tax,joining_date_time,experience_years
0,1,Amit,IT,75000.0,29,2021-03-15,Pune,67500.0,2021-03-15,4.96
1,2,Riya,HR,45000.0,26,2020-07-10,Mumbai,40500.0,2020-07-10,5.64
2,3,John,Finance,85000.0,34,2019-11-01,Bangalore,76500.0,2019-11-01,6.33
3,4,Neha,IT,65000.0,28,2022-01-20,Pune,58500.0,2022-01-20,4.11
4,5,Arjun,Marketing,40000.0,25,2021-06-18,Delhi,36000.0,2021-06-18,4.70
5,6,Priya,Finance,90000.0,36,2018-04-25,Mumbai,81000.0,2018-04-25,7.85
6,7,Karan,HR,48000.0,27,2022-09-12,Pune,43200.0,2022-09-12,3.46
7,8,Sneha,IT,72000.0,31,2020-12-05,Bangalore,64800.0,2020-12-05,5.23
8,9,Rahul,Marketing,52000.0,30,2019-02-14,Delhi,46800.0,2019-02-14,7.04
9,10,Pooja,Finance,88000.0,35,2021-08-30,Pune,79200.0,2021-08-30,4.50
10,11,Vikram,IT,60000.0,33,2018-05-21,Mumbai,54000.0,2018-05-21,7.78
11,12,Anjali,HR,45000.0,29,2023-03-11,Delhi,NaN,2023-03-11,2.97
12,13,Rohan,IT,55000.0,26,2022-11-19,Pune,49500.0,2022-11-19,3.28
13,14,Simran,Marketing,47000.0,28,2020-01-10,Bangalore,42300.0,2020-01-10,6.14
14,15,Deepak,Finance,89500.0,32,2019-09-17,Delhi,NaN,2019-09-17,6.45
15,16,Nisha,IT,80000.0,34,2017-06-23,Mumbai,72000.0,2017-06-23,8.68
16,17,Sahil,HR,42000.0,24,2023-01-05,Pune,37800.0,2023-01-05,3.15
17,18,Tina,Marketing,51000.0,29,2021-04-14,Mumbai,45900.0,2021-04-14,4.88
18,19,Varun,Finance,95000.0,38,2016-10-09,Bangalore,85500.0,2016-10-09,9.39
19,20,Meera,IT,70000.0,31,2020-02-27,Delhi,63000.0,2020-02-27,6.00

In [20]:
true_duplicates = df[df.duplicated(subset=["name", "department"])]
true_duplicates

Empty DataFrame
Columns: [emp_id, name, department, salary, age, doj, city, salary_after_tax, joining_date_time, experience_years]
Index: []

In [21]:
df2 = df.drop_duplicates()
df

,emp_id,name,department,salary,age,doj,city,salary_after_tax,joining_date_time,experience_years
0,1,Amit,IT,75000.0,29,2021-03-15,Pune,67500.0,2021-03-15,4.96
1,2,Riya,HR,45000.0,26,2020-07-10,Mumbai,40500.0,2020-07-10,5.64
2,3,John,Finance,85000.0,34,2019-11-01,Bangalore,76500.0,2019-11-01,6.33
3,4,Neha,IT,65000.0,28,2022-01-20,Pune,58500.0,2022-01-20,4.11
4,5,Arjun,Marketing,40000.0,25,2021-06-18,Delhi,36000.0,2021-06-18,4.70
5,6,Priya,Finance,90000.0,36,2018-04-25,Mumbai,81000.0,2018-04-25,7.85
6,7,Karan,HR,48000.0,27,2022-09-12,Pune,43200.0,2022-09-12,3.46
7,8,Sneha,IT,72000.0,31,2020-12-05,Bangalore,64800.0,2020-12-05,5.23
8,9,Rahul,Marketing,52000.0,30,2019-02-14,Delhi,46800.0,2019-02-14,7.04
9,10,Pooja,Finance,88000.0,35,2021-08-30,Pune,79200.0,2021-08-30,4.50
10,11,Vikram,IT,60000.0,33,2018-05-21,Mumbai,54000.0,2018-05-21,7.78
11,12,Anjali,HR,45000.0,29,2023-03-11,Delhi,NaN,2023-03-11,2.97
12,13,Rohan,IT,55000.0,26,2022-11-19,Pune,49500.0,2022-11-19,3.28
13,14,Simran,Marketing,47000.0,28,2020-01-10,Bangalore,42300.0,2020-01-10,6.14
14,15,Deepak,Finance,89500.0,32,2019-09-17,Delhi,NaN,2019-09-17,6.45
15,16,Nisha,IT,80000.0,34,2017-06-23,Mumbai,72000.0,2017-06-23,8.68
16,17,Sahil,HR,42000.0,24,2023-01-05,Pune,37800.0,2023-01-05,3.15
17,18,Tina,Marketing,51000.0,29,2021-04-14,Mumbai,45900.0,2021-04-14,4.88
18,19,Varun,Finance,95000.0,38,2016-10-09,Bangalore,85500.0,2016-10-09,9.39
19,20,Meera,IT,70000.0,31,2020-02-27,Delhi,63000.0,2020-02-27,6.00

In [22]:
df_pivot = df.groupby("department")['salary'].aggregate(['mean', 'max', 'min'])
df_pivot

                    mean      max      min
department
Finance     89500.000000  95000.0  85000.0
HR          45000.000000  48000.0  42000.0
IT          68142.857143  80000.0  55000.0
Marketing   47500.000000  52000.0  40000.0

In [23]:
import numpy as np

df['classified_salary'] = np.where(
    df['salary'] < 30000, 'Low',
    np.where(df['salary'] <= 70000, 'Medium', 'High')
)
df

,emp_id,name,department,salary,age,doj,city,salary_after_tax,joining_date_time,experience_years,classified_salary
0,1,Amit,IT,75000.0,29,2021-03-15,Pune,67500.0,2021-03-15,4.96,High
1,2,Riya,HR,45000.0,26,2020-07-10,Mumbai,40500.0,2020-07-10,5.64,Medium
2,3,John,Finance,85000.0,34,2019-11-01,Bangalore,76500.0,2019-11-01,6.33,High
3,4,Neha,IT,65000.0,28,2022-01-20,Pune,58500.0,2022-01-20,4.11,Medium
4,5,Arjun,Marketing,40000.0,25,2021-06-18,Delhi,36000.0,2021-06-18,4.70,Medium
5,6,Priya,Finance,90000.0,36,2018-04-25,Mumbai,81000.0,2018-04-25,7.85,High
6,7,Karan,HR,48000.0,27,2022-09-12,Pune,43200.0,2022-09-12,3.46,Medium
7,8,Sneha,IT,72000.0,31,2020-12-05,Bangalore,64800.0,2020-12-05,5.23,High
8,9,Rahul,Marketing,52000.0,30,2019-02-14,Delhi,46800.0,2019-02-14,7.04,Medium
9,10,Pooja,Finance,88000.0,35,2021-08-30,Pune,79200.0,2021-08-30,4.50,High
10,11,Vikram,IT,60000.0,33,2018-05-21,Mumbai,54000.0,2018-05-21,7.78,Medium
11,12,Anjali,HR,45000.0,29,2023-03-11,Delhi,NaN,2023-03-11,2.97,Medium
12,13,Rohan,IT,55000.0,26,2022-11-19,Pune,49500.0,2022-11-19,3.28,Medium
13,14,Simran,Marketing,47000.0,28,2020-01-10,Bangalore,42300.0,2020-01-10,6.14,Medium
14,15,Deepak,Finance,89500.0,32,2019-09-17,Delhi,NaN,2019-09-17,6.45,High
15,16,Nisha,IT,80000.0,34,2017-06-23,Mumbai,72000.0,2017-06-23,8.68,High
16,17,Sahil,HR,42000.0,24,2023-01-05,Pune,37800.0,2023-01-05,3.15,Medium
17,18,Tina,Marketing,51000.0,29,2021-04-14,Mumbai,45900.0,2021-04-14,4.88,Medium
18,19,Varun,Finance,95000.0,38,2016-10-09,Bangalore,85500.0,2016-10-09,9.39,High
19,20,Meera,IT,70000.0,31,2020-02-27,Delhi,63000.0,2020-02-27,6.00,Medium